import { PlanOption } from "./types";

// Plans and prices from the GrowVika brochures (prices exclusive of GST, where applicable).
export const BROCHURE_PLANS: PlanOption[] = [
  { id: "bp-website-basic", category: "Website", name: "Basic", price: 9999, cycle: "One-time" },
  { id: "bp-website-standard", category: "Website", name: "Standard", price: 14999, cycle: "One-time" },
  { id: "bp-website-business", category: "Website", name: "Business", price: 19999, cycle: "One-time" },
  { id: "bp-website-premium", category: "Website", name: "Premium", price: 34999, cycle: "One-time" },
  { id: "bp-website-e-commerce", category: "Website", name: "E-commerce", price: 49999, cycle: "One-time" },
  { id: "bp-website-care-hosting-monthly-care", category: "Website Care & Hosting", name: "Monthly Care", price: 1499, cycle: "Monthly" },
  { id: "bp-website-care-hosting-yearly-care-amc", category: "Website Care & Hosting", name: "Yearly Care (AMC)", price: 14999, cycle: "Yearly" },
  { id: "bp-website-care-hosting-hosting-renewal-basic-standard-business", category: "Website Care & Hosting", name: "Hosting Renewal (Basic / Standard / Business)", price: 2999, cycle: "Yearly" },
  { id: "bp-website-care-hosting-hosting-renewal-premium-e-commerce", category: "Website Care & Hosting", name: "Hosting Renewal (Premium / E-commerce)", price: 4999, cycle: "Yearly" },
  { id: "bp-website-seo-starter", category: "Website SEO", name: "Starter", price: 9999, cycle: "Monthly" },
  { id: "bp-website-seo-starter-6-months", category: "Website SEO", name: "Starter – 6 months", price: 56994, cycle: "Half-yearly" },
  { id: "bp-website-seo-starter-12-months", category: "Website SEO", name: "Starter – 12 months", price: 107988, cycle: "Yearly" },
  { id: "bp-website-seo-growth", category: "Website SEO", name: "Growth", price: 17999, cycle: "Monthly" },
  { id: "bp-website-seo-growth-6-months", category: "Website SEO", name: "Growth – 6 months", price: 102594, cycle: "Half-yearly" },
  { id: "bp-website-seo-growth-12-months", category: "Website SEO", name: "Growth – 12 months", price: 194388, cycle: "Yearly" },
  { id: "bp-website-seo-pro", category: "Website SEO", name: "Pro", price: 29999, cycle: "Monthly" },
  { id: "bp-website-seo-pro-6-months", category: "Website SEO", name: "Pro – 6 months", price: 170994, cycle: "Half-yearly" },
  { id: "bp-website-seo-pro-12-months", category: "Website SEO", name: "Pro – 12 months", price: 323988, cycle: "Yearly" },
  { id: "bp-website-seo-e-commerce-seo", category: "Website SEO", name: "E-commerce SEO", price: 39999, cycle: "Monthly" },
  { id: "bp-website-seo-e-commerce-seo-6-months", category: "Website SEO", name: "E-commerce SEO – 6 months", price: 227994, cycle: "Half-yearly" },
  { id: "bp-website-seo-e-commerce-seo-12-months", category: "Website SEO", name: "E-commerce SEO – 12 months", price: 431988, cycle: "Yearly" },
  { id: "bp-website-seo-business", category: "Website SEO", name: "Business", price: 49999, cycle: "Monthly" },
  { id: "bp-website-seo-business-6-months", category: "Website SEO", name: "Business – 6 months", price: 284994, cycle: "Half-yearly" },
  { id: "bp-website-seo-business-12-months", category: "Website SEO", name: "Business – 12 months", price: 539988, cycle: "Yearly" },
  { id: "bp-website-seo-seo-setup-audit", category: "Website SEO", name: "SEO Setup & Audit", price: 4999, cycle: "One-time" },
  { id: "bp-local-seo-gmb-basic", category: "Local SEO (GMB)", name: "Basic", price: 6000, cycle: "Monthly" },
  { id: "bp-local-seo-gmb-basic-6-months", category: "Local SEO (GMB)", name: "Basic – 6 months", price: 34200, cycle: "Half-yearly" },
  { id: "bp-local-seo-gmb-basic-12-months", category: "Local SEO (GMB)", name: "Basic – 12 months", price: 64800, cycle: "Yearly" },
  { id: "bp-local-seo-gmb-growth", category: "Local SEO (GMB)", name: "Growth", price: 12000, cycle: "Monthly" },
  { id: "bp-local-seo-gmb-growth-6-months", category: "Local SEO (GMB)", name: "Growth – 6 months", price: 68400, cycle: "Half-yearly" },
  { id: "bp-local-seo-gmb-growth-12-months", category: "Local SEO (GMB)", name: "Growth – 12 months", price: 129600, cycle: "Yearly" },
  { id: "bp-local-seo-gmb-daily-post", category: "Local SEO (GMB)", name: "Daily Post", price: 18000, cycle: "Monthly" },
  { id: "bp-local-seo-gmb-daily-post-6-months", category: "Local SEO (GMB)", name: "Daily Post – 6 months", price: 102600, cycle: "Half-yearly" },
  { id: "bp-local-seo-gmb-daily-post-12-months", category: "Local SEO (GMB)", name: "Daily Post – 12 months", price: 194400, cycle: "Yearly" },
  { id: "bp-local-seo-gmb-premium", category: "Local SEO (GMB)", name: "Premium", price: 25000, cycle: "Monthly" },
  { id: "bp-local-seo-gmb-premium-6-months", category: "Local SEO (GMB)", name: "Premium – 6 months", price: 142500, cycle: "Half-yearly" },
  { id: "bp-local-seo-gmb-premium-12-months", category: "Local SEO (GMB)", name: "Premium – 12 months", price: 270000, cycle: "Yearly" },
  { id: "bp-local-seo-gmb-local-seo-setup", category: "Local SEO (GMB)", name: "Local SEO Setup", price: 4999, cycle: "One-time" },
  { id: "bp-social-media-starter", category: "Social Media", name: "Starter", price: 9999, cycle: "Monthly" },
  { id: "bp-social-media-starter-6-months", category: "Social Media", name: "Starter – 6 months", price: 56994, cycle: "Half-yearly" },
  { id: "bp-social-media-starter-12-months", category: "Social Media", name: "Starter – 12 months", price: 107988, cycle: "Yearly" },
  { id: "bp-social-media-growth", category: "Social Media", name: "Growth", price: 19999, cycle: "Monthly" },
  { id: "bp-social-media-growth-6-months", category: "Social Media", name: "Growth – 6 months", price: 113994, cycle: "Half-yearly" },
  { id: "bp-social-media-growth-12-months", category: "Social Media", name: "Growth – 12 months", price: 215988, cycle: "Yearly" },
  { id: "bp-social-media-pro", category: "Social Media", name: "Pro", price: 34999, cycle: "Monthly" },
  { id: "bp-social-media-pro-6-months", category: "Social Media", name: "Pro – 6 months", price: 199494, cycle: "Half-yearly" },
  { id: "bp-social-media-pro-12-months", category: "Social Media", name: "Pro – 12 months", price: 377988, cycle: "Yearly" },
  { id: "bp-social-media-premium", category: "Social Media", name: "Premium", price: 59999, cycle: "Monthly" },
  { id: "bp-social-media-premium-6-months", category: "Social Media", name: "Premium – 6 months", price: 341994, cycle: "Half-yearly" },
  { id: "bp-social-media-premium-12-months", category: "Social Media", name: "Premium – 12 months", price: 647988, cycle: "Yearly" },
  { id: "bp-social-media-brand-setup", category: "Social Media", name: "Brand Setup", price: 4999, cycle: "One-time" },
  { id: "bp-ads-management-starter", category: "Ads Management", name: "Starter", price: 9999, cycle: "Monthly" },
  { id: "bp-ads-management-starter-6-months", category: "Ads Management", name: "Starter – 6 months", price: 56994, cycle: "Half-yearly" },
  { id: "bp-ads-management-starter-12-months", category: "Ads Management", name: "Starter – 12 months", price: 107988, cycle: "Yearly" },
  { id: "bp-ads-management-growth", category: "Ads Management", name: "Growth", price: 17999, cycle: "Monthly" },
  { id: "bp-ads-management-growth-6-months", category: "Ads Management", name: "Growth – 6 months", price: 102594, cycle: "Half-yearly" },
  { id: "bp-ads-management-growth-12-months", category: "Ads Management", name: "Growth – 12 months", price: 194388, cycle: "Yearly" },
  { id: "bp-ads-management-pro", category: "Ads Management", name: "Pro", price: 29999, cycle: "Monthly" },
  { id: "bp-ads-management-pro-6-months", category: "Ads Management", name: "Pro – 6 months", price: 170994, cycle: "Half-yearly" },
  { id: "bp-ads-management-pro-12-months", category: "Ads Management", name: "Pro – 12 months", price: 323988, cycle: "Yearly" },
  { id: "bp-ads-management-enterprise-12-of-ad-spend-min", category: "Ads Management", name: "Enterprise (12% of ad spend, min.)", price: 39999, cycle: "Monthly" },
  { id: "bp-ads-management-account-setup", category: "Ads Management", name: "Account Setup", price: 9999, cycle: "One-time" },
  { id: "bp-app-development-basic-app", category: "App Development", name: "Basic App", price: 59999, cycle: "One-time" },
  { id: "bp-app-development-business-app", category: "App Development", name: "Business App", price: 149999, cycle: "One-time" },
  { id: "bp-app-development-e-commerce-app", category: "App Development", name: "E-commerce App", price: 199999, cycle: "One-time" },
  { id: "bp-app-development-on-demand-multi-vendor", category: "App Development", name: "On-Demand / Multi-Vendor", price: 349999, cycle: "One-time" },
  { id: "bp-app-development-custom-enterprise", category: "App Development", name: "Custom / Enterprise", price: 499999, cycle: "One-time" },
  { id: "bp-app-development-app-care-basic", category: "App Development", name: "App Care Basic", price: 7999, cycle: "Monthly" },
  { id: "bp-app-development-app-care-pro", category: "App Development", name: "App Care Pro", price: 14999, cycle: "Monthly" },
  { id: "bp-app-development-app-care-enterprise", category: "App Development", name: "App Care Enterprise", price: 29999, cycle: "Monthly" },
  { id: "bp-custom-wordpress-starter", category: "Custom WordPress", name: "Starter", price: 49999, cycle: "One-time" },
  { id: "bp-custom-wordpress-pro", category: "Custom WordPress", name: "Pro", price: 79999, cycle: "One-time" },
  { id: "bp-custom-wordpress-enterprise", category: "Custom WordPress", name: "Enterprise", price: 119999, cycle: "One-time" },
  { id: "bp-php-laravel-starter", category: "PHP Laravel", name: "Starter", price: 69999, cycle: "One-time" },
  { id: "bp-php-laravel-pro", category: "PHP Laravel", name: "Pro", price: 119999, cycle: "One-time" },
  { id: "bp-php-laravel-enterprise", category: "PHP Laravel", name: "Enterprise", price: 179999, cycle: "One-time" },
  { id: "bp-next-js-react-starter", category: "Next.js / React", name: "Starter", price: 79999, cycle: "One-time" },
  { id: "bp-next-js-react-pro", category: "Next.js / React", name: "Pro", price: 149999, cycle: "One-time" },
  { id: "bp-next-js-react-enterprise", category: "Next.js / React", name: "Enterprise", price: 249999, cycle: "One-time" },
  { id: "bp-development-care-care-basic", category: "Development Care", name: "Care Basic", price: 3999, cycle: "Monthly" },
  { id: "bp-development-care-care-pro", category: "Development Care", name: "Care Pro", price: 7999, cycle: "Monthly" },
  { id: "bp-development-care-care-enterprise", category: "Development Care", name: "Care Enterprise", price: 14999, cycle: "Monthly" },
  { id: "bp-crm-php-laravel-starter", category: "CRM \u2013 PHP Laravel", name: "Starter", price: 64999, cycle: "One-time" },
  { id: "bp-crm-php-laravel-pro", category: "CRM \u2013 PHP Laravel", name: "Pro", price: 129999, cycle: "One-time" },
  { id: "bp-crm-php-laravel-enterprise", category: "CRM \u2013 PHP Laravel", name: "Enterprise", price: 169999, cycle: "One-time" },
  { id: "bp-crm-next-js-node-js-starter", category: "CRM \u2013 Next.js + Node.js", name: "Starter", price: 89999, cycle: "One-time" },
  { id: "bp-crm-next-js-node-js-pro", category: "CRM \u2013 Next.js + Node.js", name: "Pro", price: 189999, cycle: "One-time" },
  { id: "bp-crm-next-js-node-js-enterprise", category: "CRM \u2013 Next.js + Node.js", name: "Enterprise", price: 249999, cycle: "One-time" },
  { id: "bp-crm-care-crm-care-basic", category: "CRM Care", name: "CRM Care Basic", price: 4999, cycle: "Monthly" },
  { id: "bp-crm-care-crm-care-pro", category: "CRM Care", name: "CRM Care Pro", price: 9999, cycle: "Monthly" },
  { id: "bp-crm-care-crm-care-enterprise", category: "CRM Care", name: "CRM Care Enterprise", price: 19999, cycle: "Monthly" },
];

export const EXTRA_SERVICES = ["Local SEO", "App Development", "Custom Development", "CRM Development"];
