import { DB, Payment } from "./types";

const rawPayments: Omit<Payment, "id" | "invoiceNo">[] = [
  { clientId: "c1", date: "2026-07-02", amount: 20000, mode: "UPI", note: "Advance" },
  { clientId: "c1", date: "2026-08-10", amount: 15000, mode: "Bank Transfer", note: "2nd installment" },
  { clientId: "c1", date: "2026-09-12", amount: 10000, mode: "Cash", note: "3rd installment" },
  { clientId: "c2", date: "2026-07-05", amount: 15000, mode: "UPI", note: "July retainer" },
  { clientId: "c2", date: "2026-08-05", amount: 15000, mode: "UPI", note: "August retainer" },
  { clientId: "c2", date: "2026-09-05", amount: 15000, mode: "UPI", note: "September retainer" },
  { clientId: "c3", date: "2026-07-20", amount: 25000, mode: "Bank Transfer", note: "Website advance" },
  { clientId: "c3", date: "2026-08-28", amount: 20000, mode: "Bank Transfer", note: "Website 2nd part" },
  { clientId: "c4", date: "2026-08-01", amount: 12000, mode: "UPI", note: "Ads management - Aug" },
  { clientId: "c4", date: "2026-09-01", amount: 12000, mode: "UPI", note: "Ads management - Sep" },
  { clientId: "c5", date: "2026-08-18", amount: 8000, mode: "Cash", note: "Branding advance" },
  { clientId: "c6", date: "2026-06-15", amount: 30000, mode: "Cheque", note: "SEO 6 months (part 1)" },
  { clientId: "c6", date: "2026-09-20", amount: 18000, mode: "Bank Transfer", note: "SEO part 2" },
];

const sorted = [...rawPayments].sort((a, b) => a.date.localeCompare(b.date));
const payments: Payment[] = sorted.map((p, i) => ({
  ...p,
  id: `p${i + 1}`,
  invoiceNo: `GV-${String(i + 1).padStart(4, "0")}`,
}));

export const seedDB = (): DB => ({
  company: {
    name: "Growvika",
    tagline: "Digital Growth Partner",
    address: "Your office address, City, State - PIN",
    phone: "+91 98765 43210",
    email: "hello@growvika.com",
    gst: "05ABCDE1234F1Z5",
  },
  users: [
    { id: "u1", name: "Sahil (Admin)", email: "admin@growvika.com", password: "admin123", role: "admin", active: true },
    { id: "u2", name: "Riya Sharma", email: "riya@growvika.com", password: "riya123", role: "employee", active: true },
    { id: "u3", name: "Aman Verma", email: "aman@growvika.com", password: "aman123", role: "employee", active: true },
  ],
  clients: [
    {
      id: "c1", name: "Rakesh Sharma", business: "Sharma Traders", phone: "9876500011", whatsapp: "9876500011",
      email: "rakesh@sharmatraders.in", address: "Main Market, Rajpur Road", city: "Dehradun", state: "Uttarakhand",
      gst: "05AAKFS1234K1ZQ", services: ["Social Media", "Meta Ads"], status: "VIP", joinedAt: "2026-07-01",
      notes: "Sirf shaam 5 baje ke baad call karna. Hindi mein baat karna pasand hai.", assignedTo: "u2",
      totalBilling: 50000, gstApplicable: true,
    },
    {
      id: "c2", name: "Neha Gupta", business: "Gupta Sweets", phone: "9876500022", whatsapp: "9876500022",
      email: "neha@guptasweets.com", address: "Paltan Bazaar", city: "Dehradun", state: "Uttarakhand",
      gst: "", services: ["Social Media"], status: "Active", joinedAt: "2026-07-03",
      notes: "Monthly retainer ₹15,000. Har mahine 5 tareekh ko payment.", assignedTo: "u2",
      totalBilling: 45000, gstApplicable: false,
    },
    {
      id: "c3", name: "Dr. Anil Rawat", business: "Rawat Dental Clinic", phone: "9876500033", whatsapp: "9876500033",
      email: "dr.rawat@rawatdental.in", address: "GMS Road", city: "Dehradun", state: "Uttarakhand",
      gst: "05AAPFR5678M1ZT", services: ["Website", "SEO"], status: "Active", joinedAt: "2026-07-18",
      notes: "Website + local SEO. Appointment booking form chahiye tha.", assignedTo: "u3",
      totalBilling: 60000, gstApplicable: true,
    },
    {
      id: "c4", name: "Vikram Negi", business: "Himalayan Stays", phone: "9876500044", whatsapp: "9876500044",
      email: "bookings@himalayanstays.in", address: "Mall Road", city: "Mussoorie", state: "Uttarakhand",
      gst: "05AAHFH9012P1ZX", services: ["Meta Ads", "Google Ads"], status: "Active", joinedAt: "2026-07-28",
      notes: "Season mein ads budget badhana hai (Oct-Dec).", assignedTo: "u3",
      totalBilling: 36000, gstApplicable: true,
    },
    {
      id: "c5", name: "Pooja Bisht", business: "Pahadi Organics", phone: "9876500055", whatsapp: "9876500055",
      email: "pooja@pahadiorganics.com", address: "Tilak Road", city: "Rishikesh", state: "Uttarakhand",
      gst: "", services: ["Branding", "Content"], status: "Active", joinedAt: "2026-08-15",
      notes: "Logo + packaging design. Balance delivery ke baad.", assignedTo: "u2",
      totalBilling: 20000, gstApplicable: false,
    },
    {
      id: "c6", name: "Manoj Joshi", business: "Joshi Properties", phone: "9876500066", whatsapp: "9876500066",
      email: "manoj@joshiproperties.in", address: "Haridwar Road", city: "Dehradun", state: "Uttarakhand",
      gst: "05AAJFJ3456L1ZB", services: ["SEO"], status: "Inactive", joinedAt: "2026-06-10",
      notes: "SEO contract khatam. Renewal ki baat Oct mein.", assignedTo: "u1",
      totalBilling: 48000, gstApplicable: true,
    },
  ],
  payments,
  invoiceCounter: payments.length,
  leads: [
    { id: "l1", name: "Sunil Rana", business: "Rana Fitness Gym", phone: "9811100011", source: "Instagram", service: "Social Media", stage: "New Lead", followUp: "2026-09-29", assignedTo: "u2", note: "Reels chahiye gym ke liye", lostReason: "", createdAt: "2026-09-26" },
    { id: "l2", name: "Kavita Thapa", business: "Thapa Boutique", phone: "9811100022", source: "Referral", service: "Meta Ads", stage: "Contacted", followUp: "2026-09-28", assignedTo: "u2", note: "Gupta Sweets ne refer kiya", lostReason: "", createdAt: "2026-09-22" },
    { id: "l3", name: "Deepak Chauhan", business: "Chauhan Motors", phone: "9811100033", source: "Website", service: "Google Ads", stage: "Meeting Done", followUp: "2026-09-30", assignedTo: "u3", note: "Budget ₹20k/month ads ka", lostReason: "", createdAt: "2026-09-18" },
    { id: "l4", name: "Ritu Pant", business: "Pant Coaching Centre", phone: "9811100044", source: "Facebook", service: "Website", stage: "Proposal Sent", followUp: "2026-10-01", assignedTo: "u3", note: "₹35,000 ka proposal bheja", lostReason: "", createdAt: "2026-09-10" },
    { id: "l5", name: "Harish Bhatt", business: "Bhatt Hardware", phone: "9811100055", source: "Call", service: "SEO", stage: "New Lead", followUp: "2026-10-02", assignedTo: "u1", note: "", lostReason: "", createdAt: "2026-09-27" },
    { id: "l6", name: "Sonia Kapoor", business: "Kapoor Cafe", phone: "9811100066", source: "Instagram", service: "Social Media", stage: "Won", followUp: "", assignedTo: "u2", note: "Oct se start", lostReason: "", createdAt: "2026-09-01" },
    { id: "l7", name: "Arjun Mehta", business: "Mehta Electronics", phone: "9811100077", source: "Google", service: "Meta Ads", stage: "Lost", followUp: "", assignedTo: "u3", note: "", lostReason: "Budget kam tha", createdAt: "2026-08-25" },
    { id: "l8", name: "Nisha Rawat", business: "Glow Salon", phone: "9811100088", source: "Instagram", service: "Branding", stage: "Contacted", followUp: "2026-09-28", assignedTo: "u1", note: "Logo redesign", lostReason: "", createdAt: "2026-09-24" },
  ],
  comms: [
    { id: "m1", clientId: "c1", date: "2026-09-25", type: "Call", summary: "Diwali offer ke ads ki planning discuss ki.", by: "u2", nextAction: "Friday tak ad creatives bhejne hain", fileName: "" },
    { id: "m2", clientId: "c1", date: "2026-09-12", type: "WhatsApp", summary: "₹10,000 cash payment receive hua, invoice bhej diya.", by: "u1", nextAction: "", fileName: "" },
    { id: "m3", clientId: "c1", date: "2026-07-01", type: "Meeting", summary: "Onboarding meeting. ₹50,000 ka package final hua.", by: "u1", nextAction: "", fileName: "contract-sharma-traders.pdf" },
    { id: "m4", clientId: "c2", date: "2026-09-05", type: "WhatsApp", summary: "September ki content calendar approve hui.", by: "u2", nextAction: "Navratri posts schedule karne hain", fileName: "sept-calendar.pdf" },
    { id: "m5", clientId: "c3", date: "2026-09-20", type: "Email", summary: "Website ka final draft bheja review ke liye.", by: "u3", nextAction: "Feedback ka wait", fileName: "" },
    { id: "m6", clientId: "c4", date: "2026-09-22", type: "Call", summary: "October ke liye ads budget ₹30k tak badhane ki baat hui.", by: "u3", nextAction: "Naya ads plan bhejna hai", fileName: "" },
    { id: "m7", clientId: "c5", date: "2026-09-15", type: "Meeting", summary: "Logo ke 3 options dikhaye, option 2 pasand aaya.", by: "u2", nextAction: "Packaging design start karna", fileName: "logo-options.png" },
    { id: "m8", clientId: "c6", date: "2026-09-20", type: "Call", summary: "Final payment aaya. Renewal October mein discuss karenge.", by: "u1", nextAction: "1 Oct ko renewal call", fileName: "" },
  ],
  expenses: [
    { id: "e1", date: "2026-07-04", amount: 4000, where: "Meta Ads", why: "Growvika ke khud ke leads ke liye ad campaign", category: "Ads", mode: "UPI", note: "" },
    { id: "e2", date: "2026-07-10", amount: 1200, where: "Canva Pro", why: "Clients ke posts design karne ke liye", category: "Tools / Software", mode: "UPI", note: "Monthly plan" },
    { id: "e3", date: "2026-07-30", amount: 12000, where: "Freelance designer (Rohit)", why: "Rawat Dental website ka UI design", category: "Salary / Freelancer", mode: "Bank Transfer", note: "" },
    { id: "e4", date: "2026-08-01", amount: 15000, where: "Riya ki salary", why: "July salary", category: "Salary / Freelancer", mode: "Bank Transfer", note: "" },
    { id: "e5", date: "2026-08-05", amount: 3500, where: "Hostinger", why: "Rawat Dental website hosting + domain (1 saal)", category: "Tools / Software", mode: "UPI", note: "" },
    { id: "e6", date: "2026-08-10", amount: 1200, where: "Canva Pro", why: "Clients ke posts design karne ke liye", category: "Tools / Software", mode: "UPI", note: "Monthly plan" },
    { id: "e7", date: "2026-08-20", amount: 800, where: "Printing shop", why: "Visiting cards", category: "Office", mode: "Cash", note: "" },
    { id: "e8", date: "2026-09-01", amount: 15000, where: "Riya ki salary", why: "August salary", category: "Salary / Freelancer", mode: "Bank Transfer", note: "" },
    { id: "e9", date: "2026-09-06", amount: 5000, where: "Meta Ads", why: "Navratri season mein naye leads ke liye", category: "Ads", mode: "UPI", note: "" },
    { id: "e10", date: "2026-09-10", amount: 1200, where: "Canva Pro", why: "Clients ke posts design karne ke liye", category: "Tools / Software", mode: "UPI", note: "Monthly plan" },
    { id: "e11", date: "2026-09-16", amount: 2200, where: "Taxi / Fuel", why: "Himalayan Stays Mussoorie shoot ke liye travel", category: "Travel", mode: "Cash", note: "" },
    { id: "e12", date: "2026-09-24", amount: 6500, where: "Ring light + mic", why: "Client reels shoot karne ke liye equipment", category: "Equipment", mode: "UPI", note: "" },
  ],
});
